[package]
name = "socketio_example"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_socketio = "*"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = "*"

# Create this in .cargo/config.toml in your project root
[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]