name: release-binaries
on:
  push:
    branches: [ main ]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            musl-dev \
            libssl-dev \
            pkg-config \
            wget \
            build-essential \
            linux-libc-dev \
            linux-headers-$(uname -r)

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true

      - name: Download and Compile OpenSSL for musl
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w

          ./Configure no-shared no-async \
            --prefix=/usr/local/musl \
            --openssldir=/usr/local/musl \
            linux-x86_64

          make -j$(nproc)
          sudo make install_sw

          # Ensure correct library paths
          echo "/usr/local/musl/lib" | sudo tee -a /etc/ld.so.conf.d/musl.conf
          sudo ldconfig

      - name: Build binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          OPENSSL_STATIC: 1
          OPENSSL_DIR: /usr/local/musl
          OPENSSL_INCLUDE_DIR: /usr/local/musl/include
          OPENSSL_LIB_DIR: /usr/local/musl/lib
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: /usr/local/musl/lib/pkgconfig

      - name: Optimize and package binary
        run: |
          cd target/x86_64-unknown-linux-musl/release
          strip socketio_example
          chmod +x socketio_example
          tar -czvf socketio_example-linux-x86_64.tar.gz socketio_example

      - name: Upload binary
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            target/x86_64-unknown-linux-musl/release/socketio_example-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      
      - name: Build binary
        run: cargo build --release
      
      - name: Optimize and package binary
        run: |
          cd target/release
          strip socketio_example
          chmod +x socketio_example
          mkdir dmg
          mv socketio_example dmg/
          hdiutil create -fs HFS+ -srcfolder dmg -volname socketio_example socketio_example.dmg

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/socketio_example.dmg
          asset_name: socketio_example-${{ github.event.release.tag_name }}-macos-x86_64.dmg
          asset_content_type: application/x-apple-diskimage

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      
      - name: Build binary
        run: cargo build --release
      
      - name: Create ZIP archive
        run: Compress-Archive -Path target/release/socketio_example.exe -DestinationPath target/release/socketio_example-windows-x86_64.zip

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/socketio_example-windows-x86_64.zip
          asset_name: socketio_example-${{ github.event.release.tag_name }}-windows-x86_64.zip
          asset_content_type: application/zip