name: Rust Musl Static Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          musl-tools \
          musl-dev \
          build-essential \
          perl \
          linux-headers-generic \
          linux-libc-dev

    - name: Download and Build OpenSSL
      run: |
        wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
        tar xzf openssl-1.1.1w.tar.gz
        cd openssl-1.1.1w
        
        # Remove problematic include
        sed -i '/#include <linux\/mman.h>/d' crypto/mem_sec.c
        
        # Configure for musl
        ./Configure \
          -static \
          no-shared \
          no-zlib \
          no-async \
          no-engine \
          no-comp \
          linux-x86_64 \
          --prefix=/usr/local/musl \
          --openssldir=/usr/local/musl/openssl
        
        make clean
        make CC=musl-gcc
        sudo make install_sw

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Set OpenSSL environment
      run: |
        echo "OPENSSL_DIR=/usr/local/musl" >> $GITHUB_ENV
        echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

    - name: Build static binary
      run: |
        RUSTFLAGS="-C target-feature=+crt-static" \
        cargo build \
          --release \
          --target x86_64-unknown-linux-musl

    - name: Prepare artifact
      run: |
        cp target/x86_64-unknown-linux-musl/release/your_binary_name socketio_agent-linux-x86_64-static
        chmod +x socketio_agent-linux-x86_64-static

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketio-agent-linux-x86_64-static
        path: socketio_agent-linux-x86_64-static