name: Rust Linux x86_64 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on Linux x86_64
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-unknown-linux-gnu

    - name: Prepare artifact
      run: |
        cp target/x86_64-unknown-linux-gnu/release/socketio_example rust-socket-agent-linux-x86_64
        chmod +x rust-socket-agent-linux-x86_64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-socket-agent-linux-x86_64
        path: rust-socket-agent-linux-x86_64
        
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: List and prepare artifacts
      run: |
        ls -la
        find . -name "rust-socket-agent-linux-x86_64"
        cp rust-socket-agent-linux-x86_64/rust-socket-agent-linux-x86_64 ./socketio_example
        chmod +x ./socketio_example

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: socketio_example
        tag_name: v0.1.0-${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}