name: Rust Static Musl Build with OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Install musl tools and OpenSSL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          musl-tools \
          musl-dev \
          libssl-dev \
          pkg-config

    - name: Download OpenSSL
      run: |
        wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
        tar xzf openssl-1.1.1w.tar.gz

    - name: Build OpenSSL for musl
      run: |
        cd openssl-1.1.1w
        ./Configure \
          no-shared \
          no-zlib \
          no-async \
          no-comp \
          no-idea \
          no-mdc2 \
          no-rc5 \
          no-ec2m \
          no-err \
          no-ssl3 \
          no-tls \
          no-psk \
          linux-x86_64-musl
        make -j$(nproc)

    - name: Set OpenSSL environment variables
      run: |
        echo "OPENSSL_DIR=$(pwd)/openssl-1.1.1w" >> $GITHUB_ENV
        echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

    - name: Build static binary
      run: |
        RUSTFLAGS="-C target-feature=+crt-static" \
        cargo build \
          --release \
          --target x86_64-unknown-linux-musl

    - name: Prepare artifact
      run: |
        cp target/x86_64-unknown-linux-musl/release/your_binary_name socketio_agent-linux-x86_64-static
        chmod +x socketio_agent-linux-x86_64-static

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketio-agent-linux-x86_64-static
        path: socketio_agent-linux-x86_64-static