name: Build Linux ARM (aarch64)

on: [push, pull_request]

jobs:
  linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name : check os and arch
        run: |
          uname -a
          uname -m

      - name: Install system dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            musl-dev \
            libssl-dev \
            pkg-config \
            wget \
            purl \
            build-essential \
            linux-libc-dev \
            linux-headers-$(uname -r) \
            gcc-aarch64-linux-gnu \
            gcc \
            g++ \
            make \
            crossbuild-essential-arm64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-musl
          default: true

      - name: Download and Compile OpenSSL for musl
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1e.tar.gz
          tar zxf openssl-1.1.1e.tar.gz
          cd openssl-1.1.1e

          ./Configure linux-aarch64 --prefix=/opt/openssl-1.1.1e --openssldir=/opt/openssl-1.1.1e -static
          make -j$(nproc)
          make install

          file /opt/openssl-1.1.1e/bin/openssl

      - name: Build binary
        run: |
          cargo build --release --target aarch64-unknown-linux-musl
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          OPENSSL_STATIC: 1
          OPENSSL_DIR: /usr/local/musl
          OPENSSL_INCLUDE_DIR: /usr/local/musl/include
          OPENSSL_LIB_DIR: /usr/local/musl/lib
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: /usr/local/musl/lib/pkgconfig

      - name: Optimize and package binary
        run: |
          cd target/aarch64-unknown-linux-musl/release
          strip socketio_example
          chmod +x socketio_example
          tar -czvf socketio_example-linux-aarch64.tar.gz socketio_example

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: socketio_example-linux-aarch64
          path: target/aarch64-unknown-linux-musl/release/socketio_example-linux-aarch64.tar.gz
