name: Build macOS ARM & Intel

on: [push, pull_request]

jobs:
  permissions:
    contents: write
  mac-arm64:
    runs-on: macos-14  # Ensure this runner is set up for Apple Silicon (ARM64)
    steps:
      - uses: actions/checkout@v4

      - name: Check OS and Architecture
        run: |
          uname -a
          uname -m

      - name: Install System Dependencies
        run: |
          brew install openssl@1.1
          echo "export PATH=\"/opt/homebrew/opt/openssl@1.1/bin:$PATH\"" >> ~/.zshrc
          echo "export LDFLAGS=\"-L/opt/homebrew/opt/openssl@1.1/lib\"" >> ~/.zshrc
          echo "export CPPFLAGS=\"-I/opt/homebrew/opt/openssl@1.1/include\"" >> ~/.zshrc
          source ~/.zshrc

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin
          default: true

      # - name: Build OpenSSL
      #   run: |
      #     wget https://www.openssl.org/source/openssl-1.1.1e.tar.gz
      #     tar zxf openssl-1.1.1e.tar.gz
      #     cd openssl-1.1.1e

      #     ./config no-shared no-asm --prefix=/opt/openssl-1.1.1e --openssldir=/opt/openssl-1.1.1e
      #     make -j$(nproc)
      #     make install

      #     file /opt/openssl-1.1.1e/bin/openssl


      - name: Build Binary
        run: |
          cargo build --release --target aarch64-apple-darwin
        env:
          OPENSSL_STATIC: 1
          OPENSSL_DIR: /opt/openssl-1.1.1e
          OPENSSL_INCLUDE_DIR: /opt/openssl-1.1.1e/include
          OPENSSL_LIB_DIR: /opt/openssl-1.1.1e/lib
          PKG_CONFIG_PATH: /opt/openssl-1.1.1e/lib/pkgconfig

      - name: Optimize and Package Binary
        run: |
          cd target/aarch64-apple-darwin/release
          strip socketio_example
          chmod +x socketio_example
          mv socketio_example socketio_example-mac-arm64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest macOS Build
          files: target/aarch64-apple-darwin/release/socketio_example-mac-arm64
          draft: false
          prerelease: false
          body: |
            Latest macOS build from main branch
            Built on: ${{ github.event.head_commit.timestamp }}
            Commit: ${{ github.sha }}

  mac-x86_64:
    runs-on: macos-13  # Ensure this runner is set up for macOS Intel (x86_64)
    steps:
      - uses: actions/checkout@v4

      - name: Check OS and Architecture
        run: |
          uname -a
          uname -m

      - name: Install System Dependencies
        run: |
          brew install openssl@1.1
          echo "export PATH=\"/usr/local/opt/openssl@1.1/bin:$PATH\"" >> ~/.zshrc
          echo "export LDFLAGS=\"-L/usr/local/opt/openssl@1.1/lib\"" >> ~/.zshrc
          echo "export CPPFLAGS=\"-I/usr/local/opt/openssl@1.1/include\"" >> ~/.zshrc
          source ~/.zshrc

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-apple-darwin
          default: true

      # - name: Build OpenSSL
      #   run: |
      #     wget https://www.openssl.org/source/openssl-1.1.1e.tar.gz
      #     tar zxf openssl-1.1.1e.tar.gz
      #     cd openssl-1.1.1e
      #     ./Configure darwin64-x86_64-cc --prefix=/opt/openssl-1.1.1e --openssldir=/opt/openssl-1.1.1e -static
      #     make -j$(sysctl -n hw.logicalcpu)
      #     make install
      #     file /opt/openssl-1.1.1e/bin/openssl

      - name: Build Binary
        run: |
          cargo build --release --target x86_64-apple-darwin
        env:
          OPENSSL_STATIC: 1
          OPENSSL_DIR: /opt/openssl-1.1.1e
          OPENSSL_INCLUDE_DIR: /opt/openssl-1.1.1e/include
          OPENSSL_LIB_DIR: /opt/openssl-1.1.1e/lib
          PKG_CONFIG_PATH: /opt/openssl-1.1.1e/lib/pkgconfig

      - name: Optimize and Package Binary
        run: |
          cd target/x86_64-apple-darwin/release
          strip socketio_example
          chmod +x socketio_example
          mv socketio_example socketio_example-mac-x86_64
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest macOS Build
          files: target/x86_64-apple-darwin/release/socketio_example-mac-x86_64
          draft: false
          prerelease: false
          body: |
            Latest macOS build from main branch
            Built on: ${{ github.event.head_commit.timestamp }}
            Commit: ${{ github.sha }}
